### ISSUE TITLE
SensitivewordFilter的CheckSensitiveWord方法

### ISSUE THREAD

**Issue by grantzj** [gsfeng2015/Wordfilter#1]
SensitivewordFilter的CheckSensitiveWord方法感觉有点问题，查不到敏感词。
  Map nowMap = new HashMap();
        nowMap.putAll(sensitiveWordMap);
        for (int i = beginIndex; i < txt.length(); i++) {
            word = txt.charAt(i);
            nowMap = (Map) nowMap.get(word); // 获取指定key
            if (nowMap != null) { // 存在，则判断是否为最后一个
                matchFlag++; // 找到相应key，匹配标识+1
                if ("1".equals(nowMap.get("isEnd"))) { // 如果为最后一个匹配规则,结束循环，返回匹配标识数
                    break;
                }
            } else {
                if (i == txt.length() - 1) {
                    break;
                } else {
                    matchFlag = 0;
                    nowMap = new HashMap();
                    nowMap.putAll(sensitiveWordMap);
                    continue;
                }

            }
        }
我这么改了下应该可以了，不知道改的对不对

**Comment by gsfeng179** [comment]
你把你修改的代码提交以下Pull Request吧。我晚上测试一下。

**Comment by gsfeng179** [comment]
测试了一下你的代码是不对的。我已经更正了那个bug，并增加了Example，详见release-0.0.1。感谢你的使用。
